### ISSUE TITLE
Help , god please helpme , I got an error like this "Exception: ϵͳҲָ·" 

### ISSUE THREAD

**Issue by maryjeck** [sublimelsp/LSP-ruff#17]
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2023-04-11 09:58:44, next run at 2023-04-11 10:58:44 or after
Unable to start subprocess for LSP-ruff
Traceback (most recent call last):
  File "D:\sublime_text\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 241, in start_async
    plugin_class.install_or_update()
  File "D:\sublime_text\Data\Packages\lsp_utils\st3\lsp_utils\_client_handler\abstract_plugin.py", line 109, in install_or_update
    server.install_or_update()
  File "D:\sublime_text\Data\Packages\lsp_utils\st3\lsp_utils\server_pip_resource.py", line 100, in install_or_update
    self.run(self.pip_binary(), 'install', '-r', dest_requirements_txt_path, '--disable-pip-version-check')
  File "D:\sublime_text\Data\Packages\lsp_utils\st3\lsp_utils\server_pip_resource.py", line 35, in run
    raise Exception(error)
Exception: ϵͳҲָ·

**Comment by LDAP** [comment]
What's your LSP, ST and OS version?
Do you have Python installed?
Is the Python module `venv` (python3-venv in Linux repos) installed?

**Comment by maryjeck** [comment]
I use ST4 in win11 
I choose python3 in msys2, and I put the PATH to the system environment variable.

**Comment by LDAP** [comment]
What happens if you run `python -m venv` in a terminal?

**Comment by maryjeck** [comment]
python -m venv    : it show  venv: error: the following arguments are required: ENV_DIR

python -m venv .  : it create a environment.

**Comment by maryjeck** [comment]
Is it means that  " tools -> lsp -> Toggle Log Panel "   ?
It shows me nothing.

**Comment by LDAP** [comment]
@rchl Do you have an idea?

**Comment by maryjeck** [comment]
> @rchl Do you have an idea?

It seams the wrong with lsp. the lsp can,t find path of pip or python in the msys2 .

![图片](https://user-images.githubusercontent.com/4252556/231712239-e51613a2-1fcf-45f9-8801-103cd32407a8.png)

The lsp search "pip" in the path like "Scripts" ,but msys2 haven,t that path.

Can we set the ruff-lsp path in the config?

**Comment by rchl** [comment]
We can probably adjust the logic so that it works with msys2 also. Maybe instead of checking platform just check for existence of the directory.

> Can we set the ruff-lsp path in the config?

I think you might be able to override `command` in LSP-ruff.sublime-settings but you'd be loosing the benefit of this package that automatically maintains the ruff server for you.

**Comment by maryjeck** [comment]
// Settings in here override those in "LSP-ruff/LSP-ruff.sublime-settings"

{
    "command": [
        "D:\\UsrCmd\\msys64\\ucrt64\\bin\\ruff-lsp.exe"
    ],
}

I set the config like this. It also show the error

**Comment by rchl** [comment]
More like this probably `"command": ["D:\\UsrCmd\\msys64\\ucrt64\\bin\\ruff-lsp.exe"],`

**Comment by maryjeck** [comment]
> More like this probably `"command": ["D:\\UsrCmd\\msys64\\ucrt64\\bin\\ruff-lsp.exe"],`

![图片](https://user-images.githubusercontent.com/4252556/232358377-a35ac568-f53b-4018-ad01-0b96aaad033e.png)

**Comment by maryjeck** [comment]
is it fixed？

**Comment by rchl** [comment]
No and I won't be looking into it myself.

I would suggest using native python instead of msysgit.

**Comment by matresnan** [comment]
> Traceback (most recent call last): File "D:\Sublime Text\Data\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 260, in start_async plugin_class.install_or_update() File "D:\Sublime Text\Data\Lib\python38\lsp_utils_client_handler\abstract_plugin.py", line 109, in install_or_update server.install_or_update() File "D:\Sublime Text\Data\Lib\python38\lsp_utils\server_pip_resource.py", line 108, in install_or_update raise Exception('Error installing the server:\n{}'.format(error)) Exception: Error installing the server: ϵͳҲָ·
> 
> Currently, I use uv for all my Python development, so the system does not have the official Python installation package installed If I use the command “uv tool install ruff” to install ruff, but lsp-ruff cannot start properly because it needs to use pip to install and upgrade each time My request is to support uv tool to install and upgrade ruff

If the user has explicitly specified the path to the ruff binary in the settings, there is no need to use pip to check for ruff updates, which can also avoid this issue.
